# Generated by Django 4.2.28 on 2026-04-01 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('books_stationery', 'Books & Stationery'), ('id_cards', 'ID & Cards'), ('bags', 'Bags'), ('keys', 'Keys'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('last_seen', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('date_lost', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
