# Generated by Django 4.2.28 on 2026-04-06 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('found', 'Found'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(blank=True, max_length=10)),
                ('item_id', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
