# Generated by Django 4.2.28 on 2026-04-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_founditem_status_alter_lostitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('claim', 'Claim'), ('match', 'Potential Match'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
